# Generated by Django 2.0.8 on 2018-12-21 11:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import strt_users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='codice')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='descrizione')),
            ],
            options={
                'verbose_name': 'tipo di ruolo',
                'verbose_name_plural': 'tipi di ruolo',
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('code', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='codice')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='descrizione')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='data creazione')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='data ultima modifica')),
            ],
            options={
                'verbose_name': 'ruolo',
                'verbose_name_plural': 'ruoli',
            },
        ),
        migrations.RemoveField(
            model_name='memberishiptype',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='usermemberiship',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usermemberiship',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='usermemberiship',
            name='type',
        ),
        migrations.RemoveField(
            model_name='usermemberiship',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['date_joined'], 'verbose_name': 'utente', 'verbose_name_plural': 'utenti'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'ente', 'verbose_name_plural': 'enti'},
        ),
        migrations.AlterModelOptions(
            name='organizationtype',
            options={'verbose_name': 'tipo di ente', 'verbose_name_plural': 'tipi di ente'},
        ),
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', strt_users.managers.AppUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
        migrations.AddField(
            model_name='appuser',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appuser_created', to=settings.AUTH_USER_MODEL, verbose_name='creato da'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='data ultima modifica'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appuser_updated', to=settings.AUTH_USER_MODEL, verbose_name='modificato da'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data creazione'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='indirizzo email'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='fiscal_code',
            field=models.CharField(db_index=True, help_text='inserire un codice fiscale valido', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Codice fiscale errato.', regex='^(?i)(?:(?:[B-DF-HJ-NP-TV-Z]|[AEIOU])[AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}[\\dLMNP-V]{2}(?:[A-EHLMPR-T](?:[04LQ][1-9MNP-V]|[1256LMRS][\\dLMNP-V])|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM])(?:[A-MZ][1-9MNP-V][\\dLMNP-V]{2}|[A-M][0L](?:[1-9MNP-V][\\dLMNP-V]|[0L][1-9MNP-V]))[A-Z]$')], verbose_name='codice fiscale'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='cognome'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='codice'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='strt_users.OrganizationType', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='codice'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.DeleteModel(
            name='MemberishipType',
        ),
        migrations.DeleteModel(
            name='UserMemberiship',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermembership_created', to=settings.AUTH_USER_MODEL, verbose_name='creato da'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utente'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='strt_users.Organization', verbose_name='ente'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='strt_users.MembershipType', verbose_name='tipo'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermembership_updated', to=settings.AUTH_USER_MODEL, verbose_name='modificato da'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='organization_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='strt_users.OrganizationType', verbose_name='tipo di ente'),
        ),
        migrations.AlterUniqueTogether(
            name='usermembership',
            unique_together={('member', 'organization', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='membershiptype',
            unique_together={('code', 'organization_type')},
        ),
    ]
