# Generated by Django 2.2.9 on 2020-03-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assegnatario',
            options={'verbose_name_plural': 'Assegnatari'},
        ),
        migrations.AlterModelOptions(
            name='qualificaufficio',
            options={'verbose_name_plural': 'Qualifiche uffici'},
        ),
        migrations.AlterModelOptions(
            name='ufficio',
            options={'verbose_name_plural': 'Uffici'},
        ),
    ]
