# Generated by Django 2.2.9 on 2021-01-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificaufficio',
            name='is_soggetto_default',
            field=models.BooleanField(default=False, help_text='Soggetto operante di default', verbose_name='Soggetto di default'),
        ),
    ]
