# Generated by Django 2.0.8 on 2018-10-26 15:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('strt_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='codice')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='descrizione')),
            ],
            options={
                'verbose_name': 'Tipo di ruolo',
                'verbose_name_plural': 'Tipi di ruolo',
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.Group')),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='codice')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='descrizione')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
                ('membership_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strt_users.MembershipType', verbose_name='Tipo di ruolo')),
            ],
            options={
                'verbose_name': 'Ruolo',
                'verbose_name_plural': 'Ruoli',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='memberishiptype',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='usermemberiship',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usermemberiship',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='usermemberiship',
            name='type',
        ),
        migrations.RemoveField(
            model_name='usermemberiship',
            name='user',
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='codice'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='codice'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
        migrations.DeleteModel(
            name='MemberishipType',
        ),
        migrations.DeleteModel(
            name='UserMemberiship',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strt_users.Organization', verbose_name='Ente'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='organization',
            field=models.ManyToManyField(through='strt_users.UserMembership', to='strt_users.Organization', verbose_name='Ente'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='organization_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strt_users.OrganizationType', verbose_name='Tipo di ente'),
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(through='strt_users.UserMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
