# Generated by Django 2.0.8 on 2018-11-15 01:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import strt_users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0002_auto_20181026_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'ordering': ['date_joined'], 'verbose_name': 'utente', 'verbose_name_plural': 'utenti'},
        ),
        migrations.AlterModelOptions(
            name='membershiptype',
            options={'verbose_name': 'tipo di ruolo', 'verbose_name_plural': 'tipi di ruolo'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'ente', 'verbose_name_plural': 'enti'},
        ),
        migrations.AlterModelOptions(
            name='organizationtype',
            options={'verbose_name': 'tipo di ente', 'verbose_name_plural': 'tipi di ente'},
        ),
        migrations.AlterModelOptions(
            name='usermembership',
            options={'verbose_name': 'ruolo', 'verbose_name_plural': 'ruoli'},
        ),
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', strt_users.managers.AppUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='membership_type',
        ),
        migrations.AddField(
            model_name='appuser',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appuser_created', to=settings.AUTH_USER_MODEL, verbose_name='creato da'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='data ultima modifica'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appuser_updated', to=settings.AUTH_USER_MODEL, verbose_name='modificato da'),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='strt_users.MembershipType', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data creazione'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='indirizzo email'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='fiscal_code',
            field=models.CharField(db_index=True, help_text='inserire un codice fiscale valido', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Codice fiscale errato.', regex='^(?i)(?:(?:[B-DF-HJ-NP-TV-Z]|[AEIOU])[AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}[\\dLMNP-V]{2}(?:[A-EHLMPR-T](?:[04LQ][1-9MNP-V]|[1256LMRS][\\dLMNP-V])|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM])(?:[A-MZ][1-9MNP-V][\\dLMNP-V]{2}|[A-M][0L](?:[1-9MNP-V][\\dLMNP-V]|[0L][1-9MNP-V]))[A-Z]$')], verbose_name='codice fiscale'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='cognome'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='organization_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='strt_users.OrganizationType', verbose_name='tipo di ente'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='strt_users.OrganizationType', verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utente'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='strt_users.Organization', verbose_name='ente'),
        ),
    ]
