# Generated by Django 2.2.9 on 2020-04-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0002_auto_20200330_2204'),
        ('strt_users', '0003_auto_20200403_1536'),
    ]

    operations = [
    ]
