# Generated by Django 2.0.8 on 2019-05-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0006_auto_20190215_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermembership',
            unique_together={('code', 'member', 'organization', 'type')},
        ),
    ]
