# Generated by Django 2.0.8 on 2019-05-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0007_auto_20190524_1045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membershiptype',
            unique_together={('code', 'name', 'organization_type')},
        ),
    ]
