# Generated by Django 2.0.8 on 2019-06-03 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0010_auto_20190524_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='membership',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='strt_users.UserMembership'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
