# Generated by Django 2.0.8 on 2018-10-22 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('codice', models.CharField(max_length=255)),
                ('identificativo', models.CharField(max_length=255)),
                ('tipologia', models.CharField(choices=[('unknown', 'UNKNOWN'), ('operativo', 'OPERATIVO'), ('strutturale', 'STRUTTURALE')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('data_creazione', models.DateTimeField(blank=True, null=True)),
                ('data_accettazione', models.DateTimeField(blank=True, null=True)),
                ('data_avvio', models.DateTimeField(blank=True, null=True)),
                ('data_approvazione', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Piani',
            },
        ),
        migrations.CreateModel(
            name='Stato',
            fields=[
                ('codice', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(choices=[('unknown', 'UNKNOWN'), ('draft', 'DRAFT'), ('inserito', 'INSERITO'), ('avvio', 'AVVIO'), ('adozione', 'ADOZIONE'), ('approvazione', 'APPROVAZIONE'), ('pubblicazione', 'PUBBLICAZIONE')], default='draft', max_length=20)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stati',
            },
        ),
        migrations.CreateModel(
            name='StatoPianoStorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apertura', models.DateTimeField()),
                ('data_chiusura', models.DateTimeField(blank=True, null=True)),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano')),
                ('stato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Stato')),
            ],
        ),
        migrations.AddField(
            model_name='piano',
            name='stato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piani_operativi', to='modello.Stato'),
        ),
        migrations.AddField(
            model_name='piano',
            name='storico_stati',
            field=models.ManyToManyField(through='modello.StatoPianoStorico', to='modello.Stato'),
        ),
        migrations.AlterUniqueTogether(
            name='piano',
            unique_together={('nome', 'codice')},
        ),
    ]
