# Generated by Django 2.0.8 on 2019-01-08 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('codice', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(choices=[('unknown', 'UNKNOWN'), ('draft', 'DRAFT'), ('inserito', 'INSERITO'), ('avvio', 'AVVIO'), ('adozione', 'ADOZIONE'), ('approvazione', 'APPROVAZIONE'), ('pubblicazione', 'PUBBLICAZIONE')], default='draft', max_length=20)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fasi',
                'db_table': 'strt_core_fase',
            },
        ),
        migrations.CreateModel(
            name='FasePianoStorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apertura', models.DateTimeField()),
                ('data_chiusura', models.DateTimeField(blank=True, null=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Fase')),
            ],
            options={
                'db_table': 'strt_core_piano_storico_fasi',
            },
        ),
        migrations.CreateModel(
            name='Piano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('codice', models.CharField(max_length=255)),
                ('identificativo', models.CharField(max_length=255)),
                ('tipologia', models.CharField(choices=[('unknown', 'UNKNOWN'), ('operativo', 'OPERATIVO'), ('strutturale', 'STRUTTURALE'), ('variante', 'VARIANTE')], default='unknown', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('data_delibera', models.DateTimeField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(blank=True, null=True)),
                ('data_accettazione', models.DateTimeField(blank=True, null=True)),
                ('data_avvio', models.DateTimeField(blank=True, null=True)),
                ('data_approvazione', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piani_operativi', to='modello.Fase')),
                ('storico_fasi', models.ManyToManyField(through='modello.FasePianoStorico', to='modello.Fase')),
            ],
            options={
                'verbose_name_plural': 'Piani',
                'db_table': 'strt_core_piano',
            },
        ),
        migrations.AddField(
            model_name='fasepianostorico',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AlterUniqueTogether(
            name='piano',
            unique_together={('nome', 'codice')},
        ),
    ]
