# Generated by Django 2.0.8 on 2019-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piano',
            old_name='notes',
            new_name='descrizione',
        ),
        migrations.AlterField(
            model_name='piano',
            name='codice',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='piano',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='piano',
            name='identificativo',
        ),
        migrations.RemoveField(
            model_name='piano',
            name='nome',
        ),
    ]
