# Generated by Django 2.2.9 on 2020-09-08 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modello', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strt_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soggettooperante',
            name='qualifica_ufficio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strt_users.QualificaUfficio'),
        ),
        migrations.AddField(
            model_name='risorsevas',
            name='procedura_vas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraVAS'),
        ),
        migrations.AddField(
            model_name='risorsevas',
            name='risorsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='risorsepubblicazione',
            name='procedura_pubblicazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraPubblicazione'),
        ),
        migrations.AddField(
            model_name='risorsepubblicazione',
            name='risorsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='risorsepianorevpostcp',
            name='piano_rev_post_cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.PianoRevPostCP'),
        ),
        migrations.AddField(
            model_name='risorsepianorevpostcp',
            name='risorsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='risorsepianocontrodedotto',
            name='piano_controdedotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.PianoControdedotto'),
        ),
        migrations.AddField(
            model_name='risorsepianocontrodedotto',
            name='risorsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='risorsepiano',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='risorsepiano',
            name='risorsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='risorsecopianificazione',
            name='conferenza_copianificazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ConferenzaCopianificazione'),
        ),
        migrations.AddField(
            model_name='risorsecopianificazione',
            name='risorsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='risorseavvio',
            name='procedura_avvio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraAvvio'),
        ),
        migrations.AddField(
            model_name='risorseavvio',
            name='risorsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='risorseapprovazione',
            name='procedura_approvazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraApprovazione'),
        ),
        migrations.AddField(
            model_name='risorseapprovazione',
            name='risorsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='risorseadozionevas',
            name='procedura_adozione_vas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraAdozioneVAS'),
        ),
        migrations.AddField(
            model_name='risorseadozionevas',
            name='risorsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='risorseadozione',
            name='procedura_adozione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraAdozione'),
        ),
        migrations.AddField(
            model_name='risorseadozione',
            name='risorsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='risorsa',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='proceduravas',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='proceduravas',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorseVas', to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='procedurapubblicazione',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='procedurapubblicazione',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorsePubblicazione', to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='proceduraavvio',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='proceduraavvio',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorseAvvio', to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='proceduraapprovazione',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='proceduraapprovazione',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorseApprovazione', to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='proceduraadozionevas',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='proceduraadozionevas',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorseAdozioneVas', to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='proceduraadozione',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='proceduraadozione',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorseAdozione', to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='pianorevpostcp',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='pianorevpostcp',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorsePianoRevPostCP', to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='pianocontrodedotto',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='pianocontrodedotto',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorsePianoControdedotto', to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='piano',
            name='ente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strt_users.Ente', verbose_name='ente'),
        ),
        migrations.AddField(
            model_name='piano',
            name='procedura_adozione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adozione', to='modello.ProceduraAdozione'),
        ),
        migrations.AddField(
            model_name='piano',
            name='procedura_approvazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approvazione', to='modello.ProceduraApprovazione'),
        ),
        migrations.AddField(
            model_name='piano',
            name='procedura_avvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avvio', to='modello.ProceduraAvvio'),
        ),
        migrations.AddField(
            model_name='piano',
            name='procedura_pubblicazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pubblicazione', to='modello.ProceduraPubblicazione'),
        ),
        migrations.AddField(
            model_name='piano',
            name='procedura_vas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vas', to='modello.ProceduraVAS'),
        ),
        migrations.AddField(
            model_name='piano',
            name='responsabile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='piano',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorsePiano', to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='piano',
            name='soggetto_proponente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='strt_users.QualificaUfficio', verbose_name='soggetto proponente'),
        ),
        migrations.AddField(
            model_name='parereverificavas',
            name='procedura_vas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraVAS'),
        ),
        migrations.AddField(
            model_name='parereverificavas',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='parerevas',
            name='procedura_vas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraVAS'),
        ),
        migrations.AddField(
            model_name='parerevas',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='parereadozionevas',
            name='procedura_adozione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraAdozione'),
        ),
        migrations.AddField(
            model_name='parereadozionevas',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='lottocartografico',
            name='azione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotto_validato', to='modello.Azione'),
        ),
        migrations.AddField(
            model_name='lottocartografico',
            name='azione_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotto_generato', to='modello.Azione'),
        ),
        migrations.AddField(
            model_name='lottocartografico',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotto', to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='fasepianostorico',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='elaboratocartografico',
            name='lotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.LottoCartografico'),
        ),
        migrations.AddField(
            model_name='delega',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delega',
            name='delegante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='modello.SoggettoOperante'),
        ),
        migrations.AddField(
            model_name='delega',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delega+', to='strt_users.Token'),
        ),
        migrations.AddField(
            model_name='conferenzacopianificazione',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='conferenzacopianificazione',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorseCopianificazione', to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='azionereport',
            name='azione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Azione'),
        ),
        migrations.AddField(
            model_name='azione',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
    ]
