# Generated by Django 2.2.9 on 2020-05-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0002_auto_20200512_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parerevas',
            name='consultazione_vas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modello.ConsultazioneVAS'),
        ),
    ]
