# Generated by Django 2.2.9 on 2020-05-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0002_auto_20200514_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parerevas',
            name='consultazione_vas',
        ),
        migrations.DeleteModel(
            name='ConsultazioneVAS',
        ),
    ]
