# Generated by Django 2.2.9 on 2021-01-27 16:21

from django.db import migrations, models
import strt_users.enums


def remap_opreg(apps, schema_editor):
    Azione = apps.get_model('modello', 'Azione')
    for azione in Azione.objects.filter(qualifica_richiesta__in=['PIAN', 'URB']):
        azione.qualifica_richiesta = 'REGIONE'
        azione.save()

    Delega = apps.get_model('modello', 'Delega')
    for d in Delega.objects.filter(qualifica__in=['PIAN', 'URB']):
        d.qualifica = 'OPREG'
        d.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0002_auto_20200908_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azione',
            name='qualifica_richiesta',
            field=models.CharField(choices=[(strt_users.enums.QualificaRichiesta('Responsabile Comunale'), 'Responsabile Comunale'), (strt_users.enums.QualificaRichiesta('Responsabile Regionale'), 'Responsabile Regionale'), (strt_users.enums.QualificaRichiesta('AC'), 'AC'), (strt_users.enums.QualificaRichiesta('SCA'), 'SCA'), (strt_users.enums.QualificaRichiesta('Genio Civile'), 'Genio Civile'), (strt_users.enums.QualificaRichiesta('Sistema'), 'Sistema')], max_length=26),
        ),
        migrations.AlterField(
            model_name='delega',
            name='qualifica',
            field=models.CharField(choices=[(strt_users.enums.Qualifica('Operatore Comunale'), 'Operatore Comunale'), (strt_users.enums.Qualifica('Operatore Regionale'), 'Operatore Regionale'), (strt_users.enums.Qualifica('AC - Aut Competente'), 'AC - Aut Competente'), (strt_users.enums.Qualifica('SCA'), 'SCA'), (strt_users.enums.Qualifica('Genio Civile'), 'Genio Civile'), (strt_users.enums.Qualifica('Sola lettura'), 'Sola lettura')], max_length=18),
        ),
        migrations.RunPython(remap_opreg),
    ]
