# Generated by Django 2.0.8 on 2019-01-08 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0002_auto_20181221_1112'),
        ('modello', '0002_auto_20190108_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='piano',
            name='ente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='strt_users.Organization', verbose_name='ente'),
        ),
    ]
