# Generated by Django 2.2.9 on 2020-05-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0003_auto_20200512_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='azione',
            name='avvio_scadenza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='azione',
            name='scadenza',
            field=models.DateField(blank=True, null=True),
        ),
    ]
