# Generated by Django 2.2.9 on 2020-05-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0003_auto_20200521_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piano',
            name='numero_protocollo_genio_civile',
        ),
    ]
