# Generated by Django 2.0.8 on 2019-01-18 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0003_piano_ente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PianoRisorse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'strt_core_piano_risorse',
            },
        ),
        migrations.CreateModel(
            name='Risorsa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('nome', models.TextField()),
                ('file', models.FileField(max_length=500, upload_to='')),
                ('tipo', models.TextField()),
                ('dimensione', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Fase')),
            ],
            options={
                'verbose_name_plural': 'Risorse',
                'db_table': 'strt_core_risorsa',
            },
        ),
        migrations.AlterField(
            model_name='piano',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piano',
            name='last_update',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pianorisorse',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='pianorisorse',
            name='risorsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
    ]
