# Generated by Django 2.0.8 on 2019-01-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0004_auto_20190118_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PianoRisorse',
            new_name='RisorsePiano',
        ),
        migrations.AddField(
            model_name='piano',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorsePiano', to='modello.Risorsa'),
        ),
    ]
