# Generated by Django 2.2.9 on 2020-06-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0004_auto_20200619_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottocartografico',
            name='azione_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotto_generato', to='modello.Azione'),
        ),
        migrations.CreateModel(
            name='AzioneReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaggio', models.TextField()),
                ('data', models.DateTimeField()),
                ('azione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Azione')),
            ],
            options={
                'db_table': 'strt_azione_report',
            },
        ),
    ]
