# Generated by Django 2.2.9 on 2020-06-25 15:21

from django.db import migrations, models
import serapide_core.modello.enums


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0005_auto_20200625_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azione',
            name='stato',
            field=models.CharField(choices=[(serapide_core.modello.enums.StatoAzione('attesa'), 'attesa'), (serapide_core.modello.enums.StatoAzione('necessaria'), 'necessaria'), (serapide_core.modello.enums.StatoAzione('eseguita'), 'eseguita'), (serapide_core.modello.enums.StatoAzione('fallita'), 'fallita')], max_length=22),
        ),
    ]
