# Generated by Django 2.0.8 on 2019-01-25 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modello', '0006_auto_20190118_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='piano',
            name='rup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='rup'),
        ),
    ]
