# Generated by Django 2.2.9 on 2020-06-25 17:15

from django.db import migrations, models
import serapide_core.modello.enums


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0006_auto_20200625_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='azionereport',
            name='tipo',
            field=models.CharField(choices=[(serapide_core.modello.enums.TipoReportAzione('info'), 'info'), (serapide_core.modello.enums.TipoReportAzione('warn'), 'warn'), (serapide_core.modello.enums.TipoReportAzione('err'), 'err')], default=serapide_core.modello.enums.TipoReportAzione('info'), max_length=21),
        ),
    ]
