# Generated by Django 2.0.8 on 2019-01-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0007_piano_rup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piano',
            old_name='rup',
            new_name='ruolo',
        ),
    ]
