# Generated by Django 2.2.9 on 2020-06-26 10:28

from django.db import migrations, models
import serapide_core.modello.enums


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0007_azionereport_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaboratocartografico',
            name='crs',
            field=models.CharField(default='EPSG:4326', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elaboratocartografico',
            name='ingerito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elaboratocartografico',
            name='maxx',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elaboratocartografico',
            name='maxy',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elaboratocartografico',
            name='minx',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elaboratocartografico',
            name='miny',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='azione',
            name='tipologia',
            field=models.CharField(choices=[(serapide_core.modello.enums.TipologiaAzione('UNKNOWN'), 'UNKNOWN'), (serapide_core.modello.enums.TipologiaAzione('Creato Piano/Variante'), 'Creato Piano/Variante'), (serapide_core.modello.enums.TipologiaAzione('Selezione tipologia VAS'), 'Selezione tipologia VAS'), (serapide_core.modello.enums.TipologiaAzione('Pareri verifica VAS'), 'Pareri verifica VAS'), (serapide_core.modello.enums.TipologiaAzione('Emissione Provvedimento di verifica'), 'Emissione Provvedimento di verifica'), (serapide_core.modello.enums.TipologiaAzione('Pubblicazione provvedimento di verifica AC'), 'Pubblicazione provvedimento di verifica AC'), (serapide_core.modello.enums.TipologiaAzione('Pubblicazione provvedimento di verifica AP'), 'Pubblicazione provvedimento di verifica AP'), (serapide_core.modello.enums.TipologiaAzione('Invio documentazione preliminare'), 'Invio documentazione preliminare'), (serapide_core.modello.enums.TipologiaAzione('Trasmissione pareri SCA'), 'Trasmissione pareri SCA'), (serapide_core.modello.enums.TipologiaAzione('Trasmissione pareri AC'), 'Trasmissione pareri AC'), (serapide_core.modello.enums.TipologiaAzione('Redazione documenti VAS'), 'Redazione documenti VAS'), (serapide_core.modello.enums.TipologiaAzione('Trasmissione documento preliminare di verifica'), 'Trasmissione documento preliminare di verifica'), (serapide_core.modello.enums.TipologiaAzione('Avvio del Procedimento'), 'Avvio del Procedimento'), (serapide_core.modello.enums.TipologiaAzione('Contributi Tecnici'), 'Contributi Tecnici'), (serapide_core.modello.enums.TipologiaAzione('Richiesta Integrazioni'), 'Richiesta Integrazioni'), (serapide_core.modello.enums.TipologiaAzione('Integrazioni Richieste'), 'Integrazioni Richieste'), (serapide_core.modello.enums.TipologiaAzione('Formazione del Piano'), 'Formazione del Piano'), (serapide_core.modello.enums.TipologiaAzione('Protocollo Genio Civile'), 'Protocollo Genio Civile'), (serapide_core.modello.enums.TipologiaAzione('Richiesta Conferenza di copianificazione'), 'Richiesta Conferenza di copianificazione'), (serapide_core.modello.enums.TipologiaAzione('Esito conferenza di copianificazione'), 'Esito conferenza di copianificazione'), (serapide_core.modello.enums.TipologiaAzione('Trasmissione Adozione'), 'Trasmissione Adozione'), (serapide_core.modello.enums.TipologiaAzione('Pubblicazione BURT'), 'Pubblicazione BURT'), (serapide_core.modello.enums.TipologiaAzione('Osservazioni Soggetti Istituzionali'), 'Osservazioni Soggetti Istituzionali'), (serapide_core.modello.enums.TipologiaAzione('Osservazioni Regione'), 'Osservazioni Regione'), (serapide_core.modello.enums.TipologiaAzione('Upload Osservazioni Privati'), 'Upload Osservazioni Privati'), (serapide_core.modello.enums.TipologiaAzione('Controdeduzioni'), 'Controdeduzioni'), (serapide_core.modello.enums.TipologiaAzione('Piano Controdedotto'), 'Piano Controdedotto'), (serapide_core.modello.enums.TipologiaAzione('Risultanze conferenza paesaggistica'), 'Risultanze conferenza paesaggistica'), (serapide_core.modello.enums.TipologiaAzione('Revisione Piano post Conf. Paesaggistica'), 'Revisione Piano post Conf. Paesaggistica'), (serapide_core.modello.enums.TipologiaAzione('Pareri SCA'), 'Pareri SCA'), (serapide_core.modello.enums.TipologiaAzione('Parere Motivato'), 'Parere Motivato'), (serapide_core.modello.enums.TipologiaAzione('Upload elaborati VAS'), 'Upload elaborati VAS'), (serapide_core.modello.enums.TipologiaAzione('Invio documentazione per Approvazione'), 'Invio documentazione per Approvazione'), (serapide_core.modello.enums.TipologiaAzione('Attribuzione Conformità PIT'), 'Attribuzione Conformità PIT'), (serapide_core.modello.enums.TipologiaAzione('Convocazione CP'), 'Convocazione CP'), (serapide_core.modello.enums.TipologiaAzione('Pubblicazione Approvazione'), 'Pubblicazione Approvazione'), (serapide_core.modello.enums.TipologiaAzione('Convocazione Commissione Paritetica'), 'Convocazione Commissione Paritetica'), (serapide_core.modello.enums.TipologiaAzione('Compilazione Finale Monitoraggio Urbanistico'), 'Compilazione Finale Monitoraggio Urbanistico'), (serapide_core.modello.enums.TipologiaAzione('Pubblicazione Piano'), 'Pubblicazione Piano'), (serapide_core.modello.enums.TipologiaAzione('Validazione elaborati cartografici - Adozione'), 'Validazione elaborati cartografici - Adozione'), (serapide_core.modello.enums.TipologiaAzione('Processamento elaborati cartografici - Adozione'), 'Processamento elaborati cartografici - Adozione'), (serapide_core.modello.enums.TipologiaAzione('Validazione elaborati cartografici - PCD Adozione'), 'Validazione elaborati cartografici - PCD Adozione'), (serapide_core.modello.enums.TipologiaAzione('Processamento elaborati cartografici - PCD Adozione'), 'Processamento elaborati cartografici - PCD Adozione'), (serapide_core.modello.enums.TipologiaAzione('Validazione elaborati cartografici - CP Adozione'), 'Validazione elaborati cartografici - CP Adozione'), (serapide_core.modello.enums.TipologiaAzione('Processamento elaborati cartografici - CP Adozione'), 'Processamento elaborati cartografici - CP Adozione'), (serapide_core.modello.enums.TipologiaAzione('Validazione elaborati cartografici - Approvazione'), 'Validazione elaborati cartografici - Approvazione'), (serapide_core.modello.enums.TipologiaAzione('Processamento elaborati cartografici - Approvazione'), 'Processamento elaborati cartografici - Approvazione'), (serapide_core.modello.enums.TipologiaAzione('Validazione elaborati cartografici - CP Approvazione'), 'Validazione elaborati cartografici - CP Approvazione'), (serapide_core.modello.enums.TipologiaAzione('Processamento elaborati cartografici - CP Approvazione'), 'Processamento elaborati cartografici - CP Approvazione')], default=serapide_core.modello.enums.TipologiaAzione('UNKNOWN'), max_length=60),
        ),
        migrations.AlterField(
            model_name='elaboratocartografico',
            name='nome',
            field=models.TextField(default='XXX'),
            preserve_default=False,
        ),
    ]
