# Generated by Django 2.2.9 on 2020-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0008_auto_20200626_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaboratocartografico',
            name='maxx',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='elaboratocartografico',
            name='maxy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='elaboratocartografico',
            name='minx',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='elaboratocartografico',
            name='miny',
            field=models.FloatField(),
        ),
    ]
