# Generated by Django 2.2.9 on 2020-07-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0009_auto_20200626_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='risorsa',
            name='valida',
            field=models.NullBooleanField(default=None),
        ),
    ]
