# Generated by Django 2.0.8 on 2019-01-30 15:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0002_auto_20181221_1112'),
        ('modello', '0009_auto_20190125_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceduraVAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('tipologia', models.CharField(choices=[('unknown', 'UNKNOWN'), ('semplificata', 'SEMPLIFICATA'), ('verifica', 'VERIFICA'), ('procedimento', 'PROCEDIMENTO'), ('non_necessaria', 'NON_NECESSARIA')], default='unknown', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_verifica', models.DateTimeField(blank=True, null=True)),
                ('data_procedimento', models.DateTimeField(blank=True, null=True)),
                ('data_approvazione', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('verifica_effettuata', models.BooleanField(default=False)),
                ('procedimento_effettuato', models.BooleanField(default=False)),
                ('non_necessaria', models.BooleanField(default=False)),
                ('ente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='strt_users.Organization', verbose_name='ente')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano')),
            ],
            options={
                'verbose_name_plural': 'Procedure VAS',
                'db_table': 'strt_core_vas',
            },
        ),
        migrations.CreateModel(
            name='RisorseVas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedura_vas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraVAS')),
                ('risorsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa')),
            ],
            options={
                'db_table': 'strt_core_vas_risorse',
            },
        ),
        migrations.AddField(
            model_name='proceduravas',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorseVas', to='modello.Risorsa'),
        ),
    ]
