# Generated by Django 2.0.8 on 2019-02-04 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0002_auto_20181221_1112'),
        ('modello', '0010_auto_20190130_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoritaCompetenteVAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'strt_core_autorita_competente',
            },
        ),
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('tipologia', models.CharField(choices=[('unknown', 'UNKNOWN'), ('generico', 'GENERICO'), ('acvas', 'AUT_COMP_VAS'), ('sca', 'SOGGETTO_SCA')], default='unknown', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strt_users.Organization', verbose_name='ente')),
            ],
            options={
                'verbose_name_plural': 'Contatti',
                'db_table': 'strt_core_contatto',
            },
        ),
        migrations.CreateModel(
            name='SoggettiSCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modello.Piano')),
                ('soggetto_sca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modello.Contatto')),
            ],
            options={
                'db_table': 'strt_core_soggetti_sca',
            },
        ),
        migrations.AddField(
            model_name='autoritacompetentevas',
            name='autorita_competente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modello.Contatto'),
        ),
        migrations.AddField(
            model_name='autoritacompetentevas',
            name='piano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modello.Piano'),
        ),
        migrations.AddField(
            model_name='piano',
            name='autorita_competente_vas',
            field=models.ManyToManyField(related_name='autorita_competente_vas', through='modello.AutoritaCompetenteVAS', to='modello.Contatto'),
        ),
        migrations.AddField(
            model_name='piano',
            name='soggetti_sca',
            field=models.ManyToManyField(related_name='soggetti_sca', through='modello.SoggettiSCA', to='modello.Contatto'),
        ),
        migrations.AddField(
            model_name='piano',
            name='soggetto_proponente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modello.Contatto', verbose_name='soggetto proponente'),
        ),
    ]
