# Generated by Django 2.0.8 on 2019-02-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0011_auto_20190204_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='nome',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('draft', 'DRAFT'), ('anagrafica', 'ANAGRAFICA'), ('avvio', 'AVVIO'), ('adozione', 'ADOZIONE'), ('approvazione', 'APPROVAZIONE'), ('pubblicazione', 'PUBBLICAZIONE')], default='draft', max_length=20),
        ),
    ]
