# Generated by Django 2.0.8 on 2019-02-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0015_auto_20190215_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzioniPiano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Azione')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano')),
            ],
            options={
                'db_table': 'strt_core_piano_azioni',
            },
        ),
        migrations.AddField(
            model_name='piano',
            name='azioni',
            field=models.ManyToManyField(through='modello.AzioniPiano', to='modello.Azione'),
        ),
    ]
