# Generated by Django 2.0.8 on 2019-02-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0016_auto_20190215_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azione',
            options={'verbose_name_plural': 'Azioni'},
        ),
        migrations.AlterModelTable(
            name='azione',
            table='strt_core_azione',
        ),
    ]
