# Generated by Django 2.0.8 on 2019-02-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0017_auto_20190215_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='azione',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
