# Generated by Django 2.0.8 on 2019-02-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0018_azione_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azione',
            name='tipologia',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('creato_piano', 'Creato Piano'), ('parere_verifica_vas', 'Parere Verifica VAS'), ('richiesta_verifica_vas', 'Richiesta Verifica VAS'), ('avvio_consultazioni_sca', 'Avvio Consultazioni SCA'), ('avvio_procedimento', 'Avvio Procedimento'), ('formazione_del_piano', 'Formazione del Piano'), ('protocollo_genio_civile', 'Protocollo Genio Civile')], default='unknown', max_length=80),
        ),
    ]
