# Generated by Django 2.0.8 on 2019-03-01 17:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0019_auto_20190226_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultazioneVAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_scadenza', models.DateTimeField(blank=True, null=True)),
                ('data_ricezione_pareri', models.DateTimeField(blank=True, null=True)),
                ('avvio_consultazioni_sca', models.BooleanField(default=False)),
                ('procedura_vas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraVAS')),
                ('risorsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa')),
            ],
            options={
                'verbose_name_plural': 'Consultazioni VAS',
                'db_table': 'strt_core_consultazioni_vas',
            },
        ),
    ]
