# Generated by Django 2.0.8 on 2019-03-04 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0021_consultazionevas_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultazionevas',
            name='risorsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
    ]
