# Generated by Django 2.0.8 on 2019-03-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0022_auto_20190304_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultazionevas',
            name='parere_sca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parere_sca', to='modello.Risorsa'),
        ),
        migrations.AlterField(
            model_name='azione',
            name='tipologia',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('creato_piano', 'Creato Piano'), ('parere_verifica_vas', 'Parere Verifica VAS'), ('richiesta_verifica_vas', 'Richiesta Verifica VAS'), ('avvio_consultazioni_sca', 'Avvio Consultazioni SCA'), ('avvio_procedimento', 'Avvio Procedimento'), ('formazione_del_piano', 'Formazione del Piano'), ('protocollo_genio_civile', 'Protocollo Genio Civile'), ('pareri_sca', 'Pareri SCA'), ('osservazioni_enti', 'Osservazioni Enti'), ('osservazioni_regione', 'Osservazioni Regione'), ('convocazione_conferenza_copianificazione', 'Convocazione Conferenza di Copianificazione'), ('emissione_provvedimento_verifica', 'Emissione Provvedimento di Verifica'), ('pubblicazione_provvedimento_verifica', 'Pubblicazione Provvedimento di Verifica'), ('procedimento_vas', 'Procedimento VAS')], default='unknown', max_length=80),
        ),
        migrations.AlterField(
            model_name='consultazionevas',
            name='risorsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risorsa', to='modello.Risorsa'),
        ),
    ]
