# Generated by Django 2.0.8 on 2019-03-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0023_auto_20190305_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultazionevas',
            name='parere_sca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parere_sca', to='modello.Risorsa'),
        ),
        migrations.AlterField(
            model_name='consultazionevas',
            name='risorsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='risorsa', to='modello.Risorsa'),
        ),
    ]
