# Generated by Django 2.0.8 on 2019-03-06 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0025_risorsa_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RisorseConsultazioneVas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'strt_core_consultazioni_vas_risorse',
            },
        ),
        migrations.RemoveField(
            model_name='consultazionevas',
            name='parere_sca',
        ),
        migrations.RemoveField(
            model_name='consultazionevas',
            name='risorsa',
        ),
        migrations.AddField(
            model_name='risorseconsultazionevas',
            name='consultazione_vas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ConsultazioneVAS'),
        ),
        migrations.AddField(
            model_name='risorseconsultazionevas',
            name='risorsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='consultazionevas',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorseConsultazioneVas', to='modello.Risorsa'),
        ),
    ]
