# Generated by Django 2.0.8 on 2019-03-07 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modello', '0026_auto_20190306_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParereVAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_invio_parere', models.DateTimeField(blank=True, null=True)),
                ('data_ricezione_parere', models.DateTimeField(blank=True, null=True)),
                ('consultazione_vas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ConsultazioneVAS')),
                ('procedura_vas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraVAS')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'strt_core_pareri_vas',
                'verbose_name_plural': 'Pareri VAS',
            },
        ),
        migrations.AlterField(
            model_name='azione',
            name='attore',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('comune', 'Comune'), ('regione', 'Regione'), ('ac', 'AC'), ('sca', 'SCA'), ('enti', 'ENTI'), ('genio_civile', 'Genio Civile')], default='unknown', max_length=80),
        ),
        migrations.AlterField(
            model_name='azione',
            name='tipologia',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('creato_piano', 'Creato Piano'), ('parere_verifica_vas', 'Parere Verifica VAS'), ('richiesta_verifica_vas', 'Richiesta Verifica VAS'), ('avvio_consultazioni_sca', 'Avvio Consultazioni SCA'), ('avvio_procedimento', 'Avvio Procedimento'), ('formazione_del_piano', 'Formazione del Piano'), ('protocollo_genio_civile', 'Protocollo Genio Civile'), ('pareri_sca', 'Pareri SCA'), ('osservazioni_enti', 'Osservazioni Enti'), ('osservazioni_regione', 'Osservazioni Regione'), ('upload_osservazioni_privati', 'Upload Osservazioni Privati'), ('convocazione_conferenza_copianificazione', 'Convocazione Conferenza di Copianificazione'), ('emissione_provvedimento_verifica', 'Emissione Provvedimento di Verifica'), ('pubblicazione_provvedimento_verifica', 'Pubblicazione Provvedimento di Verifica'), ('procedimento_vas', 'Procedimento VAS')], default='unknown', max_length=80),
        ),
    ]
