# Generated by Django 2.0.8 on 2019-03-07 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modello', '0027_auto_20190307_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParereVerificaVAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_invio_parere', models.DateTimeField(blank=True, null=True)),
                ('data_ricezione_parere', models.DateTimeField(blank=True, null=True)),
                ('procedura_vas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraVAS')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'strt_core_pareri_verifica_vas',
                'verbose_name_plural': 'Pareri Verifica VAS',
            },
        ),
        migrations.RemoveField(
            model_name='risorseconsultazionevas',
            name='consultazione_vas',
        ),
        migrations.RemoveField(
            model_name='risorseconsultazionevas',
            name='risorsa',
        ),
        migrations.RemoveField(
            model_name='consultazionevas',
            name='risorse',
        ),
        migrations.AlterField(
            model_name='azione',
            name='tipologia',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('creato_piano', 'Creato Piano'), ('richiesta_verifica_vas', 'Richiesta Verifica VAS'), ('avvio_procedimento', 'Avvio Procedimento'), ('formazione_del_piano', 'Formazione del Piano'), ('protocollo_genio_civile', 'Protocollo Genio Civile'), ('pareri_verifica_sca', 'Pareri Verifica VAS'), ('osservazioni_enti', 'Osservazioni Enti'), ('osservazioni_regione', 'Osservazioni Regione'), ('upload_osservazioni_privati', 'Upload Osservazioni Privati'), ('convocazione_conferenza_copianificazione', 'Convocazione Conferenza di Copianificazione'), ('emissione_provvedimento_verifica', 'Emissione Provvedimento di Verifica'), ('pubblicazione_provvedimento_verifica', 'Pubblicazione Provvedimento di Verifica'), ('avvio_consultazioni_sca', 'Avvio Consultazioni SCA'), ('pareri_sca', 'Pareri SCA')], default='unknown', max_length=80),
        ),
        migrations.DeleteModel(
            name='RisorseConsultazioneVas',
        ),
    ]
