# Generated by Django 2.0.8 on 2019-03-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0028_auto_20190307_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduravas',
            name='assoggettamento',
            field=models.BooleanField(default=True),
        ),
    ]
