# Generated by Django 2.0.8 on 2019-03-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0032_auto_20190312_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduravas',
            name='data_assoggettamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
