# Generated by Django 2.0.8 on 2019-03-21 10:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0006_auto_20190215_1022'),
        ('modello', '0034_auto_20190320_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceduraAvvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('conferenza_copianificazione', models.CharField(choices=[('necessaria', 'NECESSARIA'), ('posticipata', 'POSTICIPATA'), ('non_necessaria', 'NON_NECESSARIA')], default='necessaria', max_length=20)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_scadenza_risposta', models.DateTimeField(blank=True, null=True)),
                ('garante_nominativo', models.TextField(blank=True, null=True)),
                ('garante_pec', models.EmailField(max_length=254)),
                ('ente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='strt_users.Organization', verbose_name='ente')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano')),
            ],
            options={
                'verbose_name_plural': 'Procedure Avvio',
                'db_table': 'strt_core_avvio',
            },
        ),
        migrations.CreateModel(
            name='RisorseAvvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedura_avvio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraAvvio')),
                ('risorsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa')),
            ],
            options={
                'db_table': 'strt_core_avvio_risorse',
            },
        ),
        migrations.AddField(
            model_name='proceduraavvio',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorseAvvio', to='modello.Risorsa'),
        ),
    ]
