# Generated by Django 2.0.8 on 2019-03-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0036_auto_20190321_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduraavvio',
            name='notifica_genio_civile',
            field=models.BooleanField(default=False),
        ),
    ]
