# Generated by Django 2.0.8 on 2019-03-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0037_proceduraavvio_notifica_genio_civile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltriDestinatari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altro_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modello.Contatto')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modello.Piano')),
            ],
            options={
                'db_table': 'strt_core_altri_destinatari',
            },
        ),
        migrations.CreateModel(
            name='AutoritaIstituzionali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorita_istituzionale', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modello.Contatto')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modello.Piano')),
            ],
            options={
                'db_table': 'strt_core_autorita_istituzionale',
            },
        ),
        migrations.AddField(
            model_name='piano',
            name='altri_destinatari',
            field=models.ManyToManyField(related_name='altri_destinatari', through='modello.AltriDestinatari', to='modello.Contatto'),
        ),
        migrations.AddField(
            model_name='piano',
            name='autorita_istituzionali',
            field=models.ManyToManyField(related_name='autorita_istituzionali', through='modello.AutoritaIstituzionali', to='modello.Contatto'),
        ),
    ]
