# Generated by Django 2.0.8 on 2019-03-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0039_auto_20190321_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatto',
            name='tipologia',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('generico', 'GENERICO'), ('acvas', 'AUT_COMP_VAS'), ('sca', 'SOGGETTO_SCA'), ('ente', 'ENTE'), ('genio_civile', 'GENIO_CIVILE')], default='unknown', max_length=20),
        ),
    ]
