# Generated by Django 2.0.8 on 2019-03-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0040_auto_20190322_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='piano',
            name='data_protocollo_genio_civile',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='pubblicazione_protocollo_genio_civile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
