# Generated by Django 2.0.8 on 2019-03-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0042_auto_20190325_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azione',
            name='tipologia',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('creato_piano', 'Creato Piano/Variante'), ('richiesta_verifica_vas', 'Documento Preliminare VAS'), ('pareri_verifica_sca', 'Pareri Verifica VAS'), ('emissione_provvedimento_verifica', 'Emissione Provvedimento di Verifica'), ('pubblicazione_provvedimento_verifica', 'Pubblicazione Provvedimento di Verifica'), ('avvio_consultazioni_sca', 'Avvio Consultazioni SCA'), ('pareri_sca', 'Pareri SCA'), ('avvio_esame_pareri_sca', 'Avvio Esame Pareri SCA'), ('upload_elaborati_vas', 'Upload Elaborati VAS'), ('avvio_procedimento', 'Avvio Procedimento'), ('formazione_del_piano', 'Formazione del Piano'), ('protocollo_genio_civile', 'Protocollo Genio Civile'), ('protocollo_genio_civile_id', 'Protocollo N.'), ('richiesta_conferenza_copianificazione', 'Convocazione Conferenza di Copianificazione'), ('convocazione_conferenza_copianificazione', 'Convocazione Conferenza di Copianificazione'), ('osservazioni_enti', 'Osservazioni Enti'), ('osservazioni_regione', 'Osservazioni Regione'), ('upload_osservazioni_privati', 'Upload Osservazioni Privati')], default='unknown', max_length=80),
        ),
    ]
