# Generated by Django 2.0.8 on 2019-03-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0043_auto_20190325_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduravas',
            name='tipologia',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('semplificata', 'SEMPLIFICATA'), ('verifica', 'VERIFICA'), ('procedimento', 'PROCEDIMENTO'), ('procedimento_semplificato', 'PROCEDIMENTO_SEMPLIFICATO'), ('non_necessaria', 'NON_NECESSARIA')], default='unknown', max_length=20),
        ),
    ]
