# Generated by Django 2.0.8 on 2019-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0047_risorsa_archiviata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azione',
            name='attore',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('comune', 'Comune'), ('regione', 'Regione'), ('ac', 'AC'), ('sca', 'SCA'), ('enti', 'ENTI'), ('genio_civile', 'GENIO_CIVILE')], default='unknown', max_length=80),
        ),
    ]
