# Generated by Django 2.0.8 on 2019-03-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0048_auto_20190327_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='parerevas',
            name='inviata',
            field=models.BooleanField(default=False),
        ),
    ]
