# Generated by Django 2.0.8 on 2019-03-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0049_parerevas_inviata'),
    ]

    operations = [
        migrations.AddField(
            model_name='parereverificavas',
            name='inviata',
            field=models.BooleanField(default=False),
        ),
    ]
