# Generated by Django 2.0.8 on 2019-03-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0050_parereverificavas_inviata'),
    ]

    operations = [
        migrations.AddField(
            model_name='piano',
            name='compilazione_rapporto_ambientale_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='conformazione_pit_ppr_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='monitoraggio_urbanistico_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='piano',
            name='redazione_norme_tecniche_attuazione_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
