# Generated by Django 2.0.8 on 2019-04-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0053_auto_20190404_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenzacopianificazione',
            name='piano',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='modello.Piano'),
            preserve_default=False,
        ),
    ]
