# Generated by Django 2.0.8 on 2019-04-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0054_conferenzacopianificazione_piano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenzacopianificazione',
            options={'verbose_name_plural': 'Conferenze di Copianificazione'},
        ),
    ]
