# Generated by Django 2.0.8 on 2019-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0057_auto_20190405_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduraavvio',
            name='richiesta_integrazioni',
            field=models.BooleanField(default=False),
        ),
    ]
