# Generated by Django 2.0.8 on 2019-04-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0061_auto_20190405_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduraavvio',
            name='conclusa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proceduravas',
            name='conclusa',
            field=models.BooleanField(default=False),
        ),
    ]
