# Generated by Django 2.0.8 on 2019-04-12 08:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0006_auto_20190215_1022'),
        ('modello', '0062_auto_20190408_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceduraAdozione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_delibera_adozione', models.DateTimeField(blank=True, null=True)),
                ('data_ricezione_osservazioni', models.DateTimeField(blank=True, null=True)),
                ('data_ricezione_pareri', models.DateTimeField(blank=True, null=True)),
                ('pubblicazione_burt_url', models.URLField(blank=True, default='', null=True)),
                ('pubblicazione_burt_data', models.DateTimeField(blank=True, null=True)),
                ('pubblicazione_sito_url', models.URLField(blank=True, default='', null=True)),
                ('pubblicazione_sito_data', models.DateTimeField(blank=True, null=True)),
                ('osservazioni_concluse', models.BooleanField(default=False)),
                ('conclusa', models.BooleanField(default=False)),
                ('ente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='strt_users.Organization', verbose_name='ente')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano')),
            ],
            options={
                'verbose_name_plural': 'Procedure Adozione',
                'db_table': 'strt_core_adozione',
            },
        ),
        migrations.CreateModel(
            name='RisorseAdozione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedura_adozione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraAdozione')),
                ('risorsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa')),
            ],
            options={
                'db_table': 'strt_core_adozione_risorse',
            },
        ),
        migrations.AddField(
            model_name='proceduraadozione',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorseAdozione', to='modello.Risorsa'),
        ),
    ]
