# Generated by Django 2.0.8 on 2019-04-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0067_auto_20190415_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduraadozione',
            name='url_piano_controdedotto',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
