# Generated by Django 2.0.8 on 2019-04-16 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0069_auto_20190415_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='piano',
            name='procedura_adozione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adozione', to='modello.ProceduraAdozione'),
        ),
        migrations.AddField(
            model_name='piano',
            name='procedura_avvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avvio', to='modello.ProceduraAvvio'),
        ),
        migrations.AlterField(
            model_name='piano',
            name='tipologia',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('operativo', 'OPERATIVO'), ('strutturale', 'STRUTTURALE')], default='unknown', max_length=80),
        ),
    ]
