# Generated by Django 2.0.8 on 2019-04-16 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0070_auto_20190416_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='PianoControdedotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano')),
            ],
            options={
                'db_table': 'strt_core_piano_controdedotto',
                'verbose_name_plural': 'Piano Controdedotto',
            },
        ),
        migrations.CreateModel(
            name='RisorsePianoControdedotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piano_controdedotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.PianoControdedotto')),
                ('risorsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa')),
            ],
            options={
                'db_table': 'strt_core_risorse_piano_controdedotto',
            },
        ),
        migrations.AddField(
            model_name='pianocontrodedotto',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorsePianoControdedotto', to='modello.Risorsa'),
        ),
    ]
