# Generated by Django 2.0.8 on 2019-04-16 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0072_auto_20190416_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='PianoRevPostCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano')),
            ],
            options={
                'verbose_name_plural': 'Piani Rev. post CP',
                'db_table': 'strt_core_piano_rev_post_cp',
            },
        ),
        migrations.CreateModel(
            name='RisorsePianoRevPostCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piano_controdedotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.PianoRevPostCP')),
                ('risorsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa')),
            ],
            options={
                'db_table': 'strt_core_risorse_piano_rev_post_cp',
            },
        ),
        migrations.AlterModelOptions(
            name='pianocontrodedotto',
            options={'verbose_name_plural': 'Piani Controdedotti'},
        ),
        migrations.AddField(
            model_name='pianorevpostcp',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorsePianoRevPostCP', to='modello.Risorsa'),
        ),
    ]
