# Generated by Django 2.0.8 on 2019-04-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0073_auto_20190416_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risorsepianorevpostcp',
            old_name='piano_controdedotto',
            new_name='piano_rev_post_cp',
        ),
    ]
