# Generated by Django 2.0.8 on 2019-04-17 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modello', '0074_auto_20190417_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParereAdozioneVAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_invio_parere', models.DateTimeField(blank=True, null=True)),
                ('data_ricezione_parere', models.DateTimeField(blank=True, null=True)),
                ('inviata', models.BooleanField(default=False)),
                ('procedura_adozione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraAdozione')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'db_table': 'strt_core_pareri_adozione_vas',
                'verbose_name_plural': 'Pareri Adozione VAS',
            },
        ),
    ]
