# Generated by Django 2.0.8 on 2019-04-18 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0006_auto_20190215_1022'),
        ('modello', '0078_auto_20190417_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceduraApprovazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_delibera_approvazione', models.DateTimeField(blank=True, null=True)),
                ('richiesta_conferenza_paesaggistica', models.BooleanField(default=False)),
                ('url_piano_pubblicato', models.URLField(blank=True, default='', null=True)),
                ('conclusa', models.BooleanField(default=False)),
                ('ente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='strt_users.Organization', verbose_name='ente')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano')),
            ],
            options={
                'verbose_name_plural': 'Procedure Approvazione',
                'db_table': 'strt_core_approvazione',
            },
        ),
        migrations.CreateModel(
            name='RisorseApprovazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedura_approvazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraApprovazione')),
                ('risorsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa')),
            ],
            options={
                'db_table': 'strt_core_approvazione_risorse',
            },
        ),
        migrations.AddField(
            model_name='proceduraapprovazione',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorseApprovazione', to='modello.Risorsa'),
        ),
        migrations.AddField(
            model_name='piano',
            name='procedura_approvazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approvazione', to='modello.ProceduraApprovazione'),
        ),
    ]
