# Generated by Django 2.0.8 on 2019-04-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0083_auto_20190419_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piano',
            name='tipologia',
            field=models.CharField(choices=[('unknown', 'UNKNOWN'), ('operativo', 'OPERATIVO'), ('strutturale', 'STRUTTURALE'), ('variante_operativo', 'VARIANTE_OPERATIVO'), ('variante_strutturale', 'VARIANTE_STRUTTURALE')], default='unknown', max_length=80),
        ),
    ]
