# Generated by Django 2.0.8 on 2019-04-24 12:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('strt_users', '0006_auto_20190215_1022'),
        ('modello', '0084_auto_20190424_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceduraPubblicazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_pubblicazione', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default='', null=True)),
                ('conclusa', models.BooleanField(default=False)),
                ('ente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='strt_users.Organization', verbose_name='ente')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Piano')),
            ],
            options={
                'verbose_name_plural': 'Procedure Pubblicazione',
                'db_table': 'strt_core_pubblicazione',
            },
        ),
        migrations.CreateModel(
            name='RisorsePubblicazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedura_pubblicazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.ProceduraPubblicazione')),
                ('risorsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modello.Risorsa')),
            ],
            options={
                'db_table': 'strt_core_pubblicazione_risorse',
            },
        ),
        migrations.AddField(
            model_name='procedurapubblicazione',
            name='risorse',
            field=models.ManyToManyField(through='modello.RisorsePubblicazione', to='modello.Risorsa'),
        ),
    ]
