# Generated by Django 2.0.8 on 2019-04-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0087_auto_20190426_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceduraapprovazione',
            old_name='pubblicazione_sito_url',
            new_name='pubblicazione_url',
        ),
        migrations.RenameField(
            model_name='proceduraapprovazione',
            old_name='pubblicazione_sito_data',
            new_name='pubblicazione_url_data',
        ),
        migrations.RenameField(
            model_name='procedurapubblicazione',
            old_name='url',
            new_name='pubblicazione_url',
        ),
        migrations.AddField(
            model_name='procedurapubblicazione',
            name='pubblicazione_url_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
