# Generated by Django 2.0.8 on 2020-01-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0091_auto_20190826_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduraavvio',
            name='conferenza_copianificazione',
            field=models.CharField(blank=True, choices=[('necessaria', 'NECESSARIA'), ('posticipata', 'POSTICIPATA'), ('non_necessaria', 'NON_NECESSARIA')], default=None, max_length=20, null=True),
        ),
    ]
