# Generated by Django 2.0.8 on 2020-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modello', '0092_239_conferenza_copianificazione_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceduravas',
            name='assoggettamento',
            field=models.NullBooleanField(default=None),
        ),
    ]
