# Generated by Django 2.0.8 on 2018-12-21 15:43

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('strt_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='body',
            field=wagtail.core.fields.StreamField([('First_section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('subtitle', wagtail.core.blocks.CharBlock(required=False)), ('text', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('button_text', wagtail.core.blocks.CharBlock(required=False))], blank=True, verbose_name='Fisrt section block'))]),
        ),
    ]
