# Generated by Django 2.0.8 on 2019-07-24 09:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('strt_portal', '0004_auto_20190326_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='main_title',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
